---

- name: Get all request kubelet node token
  shell: |
    {{ dir.bin }}/kubectl --kubeconfig={{ kubernetes.config.admin }} \
      get csr | awk '/Pending/ {print $1}'
  delegate_to: "{{ groups['masters'][0] }}"
  register: request_tokens
  ignore_errors: true

- name: Approve all request kubelet
  when: request_tokens.stdout_lines|length > 0
  command: |
    {{ dir.bin }}/kubectl --kubeconfig={{ kubernetes.config.admin }} \
      certificate approve {{ item }}
  delegate_to: "{{ groups['masters'][0] }}"
  with_items: "{{ request_tokens.stdout_lines }}"
  register: approve_result
  until: approve_result.rc == 0
  retries: 5
  delay: 2
