---
# Ceph cluster on Kubernetes

ceph_image_tag: "tag-build-master-kraken-ubuntu-16.04"
rgw_external_vip: "{{ lb_vip_address }}"
rgw_external_port: "8080"

restapi_external_vip: "{{ lb_vip_address }}"
restapi_external_port: "5000"

osd_cluster_network: "{{ pod_network_cidr }}"
osd_public_network: "{{ osd_cluster_network }}"
