---

- name: "Copy {{ cni.name }} network config"
  template:
    src: "{{ cni.name }}/{{ cni.template.config }}.j2"
    dest: "{{ kubernetes.dir.network }}/{{ cni.template.config }}"
  run_once: true
  delegate_to: "{{ groups['etcds'][0] }}"

- name: Load the Flannel network config into Etcd
  shell: |
    {{ dir.bin }}/etcdctl \
      --ca-file={{ etcd.certs.ca }} \
      --cert-file={{ etcd.certs.cert }} \
      --key-file={{ etcd.certs.cert_key }} \
      --no-sync \
      --peers={{ etcd_endpoints }} \
      set {{ conf_loc }} < {{ kubernetes.dir.network }}/{{ cni.template.config }}
  run_once: true
  delegate_to: "{{ groups['etcds'][0] }}"
