---
# Require the cluster is fully operation and running

- hosts: cluster
  become: yes
  roles:
    - { role: storage/ceph, tags: ceph }

# - hosts: masters
#   gather_facts: no
#   become: yes
#   roles:
#     - { role: storage/ceph-k8s, tags: ceph-k8s }
