---
- hosts: global
  gather_facts: no
  become: yes
  tasks:
    - raw: ln -s /usr/bin/python3 /usr/bin/python
      ignore_errors: yes

- hosts: all
  gather_facts: no
  become: no
  roles:
    - { role: local/sslcert, tags: cert }

- hosts: cluster
  become: yes
  roles:
    - { role: common/base, tags: base }
    - { role: common/docker, tags: docker }
    - { role: kubernetes/storage/ceph, tags: ceph, when: ceph == 'true' }

- hosts: masters
  become: yes
  roles:
    - { role: kubernetes/etcd, tags: etcd }
    - { role: kubernetes/ha, tags: ha }
    - { role: kubernetes/master, tags: master }
    - { role: kubernetes/addon, when: kube_proxy, addon: "{{ addons.proxy }}", tags: kube-proxy }
    - { role: kubernetes/addon, when: kube_dns, addon: "{{ addons.dns }}", tags: kube-dns }
    - { role: kubernetes/cni, tags: cni }
    - { role: kubernetes/storage/ceph-k8s, tags: ceph-k8s, when: ceph == 'true' }
    - { role: kubernetes/addon, addon: "{{ addons.dashboard }}", tags: dashboard, when: kube_dashboard }
    - { role: kubernetes/addon, addon: "{{ addons.logging }}", tags: logging, when: kube_logging }
    - { role: kubernetes/addon, addon: "{{ addons.monitoring }}", tags: monitoring, when: kube_monitoring }
    - { role: kubernetes/addon, addon: "{{ addons.default_backend }}", tags: default_backend, when: ingress and (ingress_type == 'haproxy' or ingress_type == 'nginx') }
    - { role: kubernetes/addon, addon: "{{ addons.ingress[ingress_type] }}", tags: ingress, when: ingress }
    # - { role: kubernetes/addon, addon: "{{ addons.watch }}", tags: watch, when: kube_watch }

- hosts: nodes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }
