dependencies:
  - { role: commons/packages, pkg: "{{ downloads.kubelet }}" }
  - { role: commons/packages, pkg: "{{ downloads.helm }}" }
  - { role: commons/packages, pkg: "{{ downloads.cni }}" }
  - { role: commons/packages, pkg: "{{ downloads.calicoctl }}", when: network == 'calico' or network == 'canal'}
  - { role: commons/container-images, img: "{{ images.pod_infra }}", pre_pull: false }
  - { role: commons/container-images, img: "{{ images.apiserver }}" }
  - { role: commons/container-images, img: "{{ images.manager }}" }
  - { role: commons/container-images, img: "{{ images.scheduler }}" }
