---

- name: Configure Etcd key/value store
  import_tasks: config.yml

- name: Init Etcd systemd service
  import_tasks: systemd.yml

- name: Enable and restart Etcd
  systemd:
    name: etcd
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_etcd
