---

- name: Create Etcd system group
  group:
    name: etcd
    state: present

- name: Create Etcd system user
  user:
    name: etcd
    comment: "Etcd user"
    shell: /sbin/nologin
    state: present
    system: yes
    groups: etcd

- name: "Ensure {{ etcd_data_dir }} already exists"
  file:
    path: "{{ etcd_data_dir }}"
    recurse: yes
    state: directory
    owner: etcd

- name: Copy Etcd systemd service file
  template: src=etcd.service.j2 dest={{ systemd_dir }}/etcd.service owner=root group=root mode=0755
  register: change_etcd
