---
    
- name: Set ceph-addon directory path variable
  set_fact:
    ceph_addon_dir: "{{ kube_addon_dir }}/ceph"

- name: Create kubernetes ceph-addon directory
  file: path="{{ ceph_addon_dir }}" state=directory

- name: Copy kubernetes ceph-addon config file
  template: src={{ item.src }} dest={{ ceph_addon_dir }}/{{ item.dest }}
  with_items:
    - { src: "ceph-mds-dp.yml.j2", dest: "ceph-mds-dp.yml" }
    - { src: "ceph-mon-check-dp.yml.j2", dest: "ceph-mon-check-dp.yml" }
    - { src: "ceph-mon-dp.yml.j2", dest: "ceph-mon-dp.yml" }
    - { src: "ceph-osd-ds.yml.j2", dest: "ceph-osd-ds.yml" }

- name: Check ceph mds deployment
  shell: "kubectl get deploy --namespace=ceph | grep ceph-mds"
  delegate_to: "{{ groups['masters'][0] }}"
  register: check_ceph_mds
  ignore_errors: true
  run_once: true

- name: Create ceph mds deployment
  when: check_ceph_mds|failed
  shell: "kubectl create --kubeconfig={{ kubeadmin_config }} -f {{ ceph_addon_dir }}/ceph-mds-dp.yml"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true

- name: Check mon check deployment
  shell: "kubectl get deploy --namespace=ceph | grep ceph-mon-check"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
  register: check_ceph_mon_health
  ignore_errors: true

- name: Create mon check deployment
  when: check_ceph_mon_health|failed
  shell: "kubectl create --kubeconfig={{ kubeadmin_config }} -f {{ ceph_addon_dir }}/ceph-mon-check-dp.yml"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true

- name: Check mon deployment
  shell: "kubectl get deploy --namespace=ceph | awk '{ print $1}' | grep ceph-mon$"
  delegate_to: "{{ groups['masters'][0] }}"
  register: check_ceph_mon
  ignore_errors: true
  run_once: true

- name: Create mon deployment
  when: check_ceph_mon|failed
  shell: "kubectl create --kubeconfig={{ kubeadmin_config }} -f {{ ceph_addon_dir }}/ceph-mon-dp.yml"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true

- name: Check osd daemonset
  shell: "kubectl get ds --namespace=ceph | grep ceph-osd"
  delegate_to: "{{ groups['masters'][0] }}"
  register: check_ceph_osd
  ignore_errors: true
  run_once: true

- name: Create osd daemonset
  when: check_ceph_osd|failed
  shell: "kubectl create --kubeconfig={{ kubeadmin_config }} -f {{ ceph_addon_dir }}/ceph-osd-ds.yml"
  delegate_to: "{{ groups['masters'][0] }}"
  run_once: true
