---

- name: "Check {{ pkg.description }} binary already exists"
  when: pkg is defined
  stat: path="{{ download_tmp }}/{{ item.file }}-{{ bases[''+ pkg.name].version }}"
  with_items: "{{ pkg['items'] }}"
  register: pkg_check

- name: "Downloading {{ pkg.description }} binaries"
  when: 'pkg is defined and not item.stat.exists'
  get_url:
    url: "{{ pkg.url }}/{{ item.item.file }}"
    dest: "{{ download_tmp }}/{{ item.item.file }}-{{ bases[''+ pkg.name].version }}"
    validate_certs: False
  with_items: "{{ pkg_check.results }}"
  register: pkg_download

- name: "Copy {{ pkg.description }} file to release directory"
  when: pkg is defined
  copy:
    src: "{{ download_tmp }}/{{ item.file }}-{{ bases[''+ pkg.name].version }}"
    dest: "{{ pkg.dir }}/{{ item.symlink }}"
    owner: root
    group: root
    mode: 0755
    remote_src: True
  with_items: "{{ pkg['items'] }}"
  register: pkg_copy
