---

images:
  pod_infra: # registry.access.redhat.com/rhel7/pod-infrastructure
    name: pause
    repos: gcr.io/google_containers/
    tag: "3.1"
  apiserver:
    name: kube-apiserver-amd64
    repos: gcr.io/google_containers/
    tag: "v{{ kube_version }}"
  manager:
    name: kube-controller-manager-amd64
    repos: gcr.io/google_containers/
    tag: "v{{ kube_version }}"
  scheduler:
    name: kube-scheduler-amd64
    repos: gcr.io/google_containers/
    tag: "v{{ kube_version }}"
  haproxy:
    name: haproxy
    repos: kairen/
    tag: "1.7"
  keepalived:
    name: keepalived
    repos: kairen/
    tag: "1.2.24"
