---

- name: Configure Docker container engine
  import_tasks: config.yml

- name: Init Docker systemd service
  import_tasks: systemd.yml

- name: Enable and start Docker socket
  when: change_socket|succeeded
  systemd:
    name: docker.socket
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_socket
  notify:
    - Delete docker0 interface
    - Enable and restart Docker engine
    - Wait for repository server start
