---

- name: Create Docker system group
  group:
    name: docker
    state: present

- name: Create Docker system  user
  user:
    name: docker
    comment: "Docker user"
    shell: /sbin/nologin
    state: present
    system: yes
    groups: docker

- name: Copy Docker socket service file
  register: change_socket
  copy:
    src: docker.socket
    dest: "{{ systemd_dir }}/docker.socket"
    owner: root
    group: root
    mode: 0755

- name: Copy Docker engine service file
  register: change_docker
  template:
    src: "docker.service.j2"
    dest: "{{ systemd_dir }}/docker.service"
    owner: root
    group: root
    mode: 0755
