---

bin_dir: /usr/local/bin
sbin_dir: /usr/local/sbin
cache_dir: /tmp
ld_config_dir: /etc/ld.so.conf.d

systemd_service_dir: /lib/systemd/system
systemd_env_dir: /etc/default
systemd_dropin_dir: /etc/systemd/system
