---

bin_dir: /usr/local/bin
sbin_dir: /usr/local/sbin
cache_dir: /tmp

systemd_service_dir: /lib/systemd/system
systemd_env_dir: /etc/default
systemd_dropin_dir: /etc/systemd/system

docker_data_dir: /var/lib/docker
